services:
  
  postgres:
    image: postgres:16.2
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    environment:
      - POSTGRES_DB=demo_postgres
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    ports:
      - "20001:5432"
  
  phppgadmin:
    build:
      context: ../container/phppgadmin
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_phppgadmin
    container_name: ${COMPOSE_PROJECT_NAME}_phppgadmin
    ports:
      - "30008:8080"
    links:
      - postgres:postgres
    environment:
      DATABASE_HOST: postgres
